# Generated by Django 3.0.6 on 2020-05-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('EMAIL_ME_A_RECEIPT', models.BooleanField(default=True, verbose_name='EMAIL ME A RECEIPT')),
                ('GIVE_ANONYMOUSLY', models.BooleanField(default=False, verbose_name='GIVE ANONYMOUSLY')),
                ('ADD_ME_TO_EMAIL_LIST', models.BooleanField(default=False, verbose_name='ADD ME TO EMAIL LIST')),
            ],
        ),
    ]
